# Generated by Django 6.0 on 2026-01-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_year_studentprofile_graduation_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='company_size',
            field=models.CharField(blank=True, help_text='e.g. 1-10, 11-50, 51-200', max_length=50),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='founded_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='headquarters',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='hr_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='hr_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='industry',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='linkedin_page',
            field=models.URLField(blank=True),
        ),
    ]
