# Generated by Django 6.0 on 2026-04-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='project_visibility',
            field=models.CharField(choices=[('all', 'Everyone'), ('recruiters', 'Only Recruiters'), ('private', 'Only Me')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='show_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='project_visibility',
            field=models.CharField(choices=[('all', 'Everyone'), ('recruiters', 'Only Recruiters'), ('private', 'Only Me')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='show_email',
            field=models.BooleanField(default=False),
        ),
    ]
