# Generated by Django 6.0 on 2026-04-03 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_companyprofile_is_public_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='project_visibility',
        ),
    ]
