# Generated by Django 6.0 on 2026-04-01 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_rename_recipient_notification_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
